modLoader="javafml" 
license="GNU LESSER GENERAL PUBLIC LICENSE" 
loaderVersion="[36,)" 
issueTrackerURL="https://github.com/HungTeen/pvzmod/issues"

[[mods]]
modId="pvz"
version="0.6.5.1"
displayName="Plants vs Zombies 95V"
authors="SuSen36,_HungTeen_, Wolf__Crystal, Grass_Carp"
logoFile="logo.png" 
displayURL="https://github.com/Lzc-SuSen/htpvz95"
credits="Men_Tian_Bai, InkyTheSheep, Chompy, XXTT, 136(some of challenges), True Bebra(Russian translation) and so on."
description="A mod that brings Plants vs Zombies 95Version to Minecraft !"
configBackground="pvz:textures/block/amethyst_block.png"

[[dependencies.pvz]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    
[[dependencies.pvz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"